'use strict';
// resource
export const RESOURCE_LIST = 'resourceList';
export const GET_RULE = 'getRule';

// rule
export const API_ZHUI_SHU = 'apiZhuiShu';
export const NET_ZHAN_NEI = 'netZhanNei';
export const NET_BAI_DU = 'netBaiDu';
export const API_PROPHET = 'apiProphet';

// search
export const SEARCH_HOT_WORDS = 'SEARCH_HOT_WORDS';
export const SEARCH_REFRESH_HOT_WORDS = 'SEARCH_REFRESH_HOT_WORDS';
export const SEARCH_AUTO_COMPLETE = 'SEARCH_AUTO_COMPLETE';
export const SEARCH_SEARCH_BOOKS = 'SEARCH_SEARCH_BOOKS';
export const SEARCH_BACK_TO_INIT_STATE = 'SEARCH_BACK_TO_INIT_STATE';
export const SEARCH_BOOK_WIDTH_NET = 'searchBookWidthNet';
export const SEARCH_BOOK_WITH_ENGINE = 'searchBookWithEngine';
export const GET_CATALOGUE_WITH_CRAWLER = 'getCatalogueWithCrawler';
export const GET_CONTENT_WITH_CRAWLER = 'getContentWithCrawler';
export const GET_CATALOGUE_WITH_DS = 'getCatalogueWithDs';
export const SET_CHAPTER_PAGE = 'setChapterPage';
export const GET_BOOK_STORE = 'getBookStore';
export const UPDATE_BOOK_STORE = 'updateBookStore';
export const STORE_BOOK = 'storeBook';
export const SAVE_BOOK = 'saveBook';
export const LOAD_BOOK = 'loadBook';
export const READ_BOOK = 'readBook';
export const REMOVE_BOOK = 'removeBook';
export const REMOVE_CHAPTER = 'removeChapter';
export const LOAD_CONTENT = 'loadContent';

// bookDetailAction
export const BOOK_DETAIL = 'BOOK_DETAIL';
export const BOOK_DETAIL_LOADING = 'BOOK_DETAIL_LOADING';
export const BOOK_HOT_REVIEW = 'BOOK_HOT_REVIEW';
export const BOOK_RECOMMEND_BOOK_LIST = 'BOOK_RECOMMEND_BOOK_LIST';

// book -- bookCommunity
export const BOOK_DISCUSSION_LIST = 'BOOK_DISCUSSION_LIST';
export const BOOK_DISCUSSION_LIST_LOADING = 'BOOK_DISCUSSION_LIST_LOADING';
export const BOOK_REVIEW_LIST = 'BOOK_REVIEW_LIST';
export const BOOK_REVIEW_LIST_LOADING = 'BOOK_REVIEW_LIST_LOADING';

// readPlatformAction

// discover -- charts
export const DISCOVER_CHARTS_LOADING = 'DISCOVER_CHARTS_LOADING';
export const DISCOVER_CHARTS = 'DISCOVER_CHARTS';
export const DISCOVER_CHARTS_DETAIL_LOADING = 'DISCOVER_CHARTS_DETAIL_LOADING';
export const DISCOVER_CHARTS_DETAIL = 'DISCOVER_CHARTS_DETAIL';

// discover -- bookList
export const DISCOVER_BOOK_LIST_LOADING = 'DISCOVER_BOOK_LIST_LOADING';
export const DISCOVER_BOOK_LIST = 'DISCOVER_BOOK_LIST';
export const DISCOVER_CATEGORY_LIST_LOADING = 'DISCOVER_CATEGORY_LIST_LOADING';
export const DISCOVER_CATEGORY_LIST = 'DISCOVER_CATEGORY_LIST';
export const DISCOVER_CATEGORY_LIST_V2 = 'DISCOVER_CATEGORY_LIST_V2';

// community -- community
export const COMMUNITY_BOOK_DISCUSSION_LIST_LOADING =
  'COMMUNITY_BOOK_DISCUSSION_LIST_LOADING';
export const COMMUNITY_BOOK_DISCUSSION_LIST = 'COMMUNITY_BOOK_DISCUSSION_LIST';
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING =
  'COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING';
export const COMMUNITY_BOOK_DISCUSSION_DETAIL =
  'COMMUNITY_BOOK_DISCUSSION_DETAIL';
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST =
  'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST';
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING =
  'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING';
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST =
  'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST';

// community -- review
export const COMMUNITY_BOOK_REVIEW_LIST_LOADING =
  'COMMUNITY_BOOK_REVIEW_LIST_LOADING';
export const COMMUNITY_BOOK_REVIEW_LIST = 'COMMUNITY_BOOK_REVIEW_LIST';
export const COMMUNITY_BOOK_REVIEW_DETAIL_LOADING =
  'COMMUNITY_BOOK_REVIEW_DETAIL_LOADING';
export const COMMUNITY_BOOK_REVIEW_DETAIL = 'COMMUNITY_BOOK_REVIEW_DETAIL';
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST =
  'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST';
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING =
  'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING';
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST =
  'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST';

// community -- review
export const COMMUNITY_BOOK_HELP_LIST_LOADING =
  'COMMUNITY_BOOK_HELP_LIST_LOADING';
export const COMMUNITY_BOOK_HELP_LIST = 'COMMUNITY_BOOK_HELP_LIST';
export const COMMUNITY_BOOK_HELP_DETAIL_LOADING =
  'COMMUNITY_BOOK_HELP_DETAIL_LOADING';
export const COMMUNITY_BOOK_HELP_DETAIL = 'COMMUNITY_BOOK_HELP_DETAIL';
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST =
  'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST';
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING =
  'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING';
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST =
  'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST';
